import {build} from 'esbuild';
import {readFile,writeFile,copyFile,mkdir,cp} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
const source=fileURLToPath(new URL('./src/app.mjs',import.meta.url));
const destination=fileURLToPath(new URL('./dist/',import.meta.url));
await mkdir(destination,{recursive:true});
await cp(new URL("./public/",import.meta.url),destination,{recursive:true});
await writeFile(destination+".nojekyll", "");
await build({entryPoints:[source],bundle:true,format:'esm',platform:'browser',target:'es2022',outfile:destination+'app.js',legalComments:'eof'});
await copyFile(new URL('./node_modules/jose/LICENSE.md',import.meta.url),destination+'JOSE-LICENSE.txt');
await copyFile(destination+'index.html',destination+'callback.html');
const assets=['index.html','callback.html','arrival.js','app.js','style.css','icon.svg','manifest.webmanifest'];
const hash=createHash('sha256');for(const path of assets)hash.update(await readFile(destination+path));
const version=hash.digest('hex').slice(0,16);
await writeFile(destination+'sw.js',`// Generated by build.mjs. No OAuth or API traffic is cached.
const CACHE='browser-auth-probe-${version}';
const ASSETS=${JSON.stringify(assets)};
const base=new URL('./',self.location.href);
const allowed=new Set(ASSETS.map(p=>new URL(p,base).href));
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll([...allowed]))));
// Waiting workers activate on the next fresh page session, never mid-grant.
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(names=>Promise.all(names.filter(n=>n.startsWith('browser-auth-probe-')&&n!==CACHE).map(n=>caches.delete(n)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{
 const url=new URL(event.request.url);
 if(event.request.method!=='GET'||url.origin!==base.origin)return;
 const clean=new URL(url.pathname,base.origin).href;
 if(!allowed.has(clean))return;
 // callback?code=... maps to cached callback.html. Never put query-bearing
 // requests into the cache or forward them from the service worker.
 event.respondWith(caches.open(CACHE).then(async cache=>(await cache.match(clean))||fetch(clean,{credentials:'omit'})));
});
`);
console.log(`Built static PWA (${version}). No runtime CDN dependencies.`);
